# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=140)),
                ('long_description', models.TextField()),
                ('visual_representation', models.TextField()),
                ('geojson_url', models.CharField(max_length=511)),
                ('mapbox_aux', models.TextField()),
            ],
            options={
                'ordering': ('short_description', 'long_description'),
            },
        ),
    ]
