# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_api', '0003_queryobject_query_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryobject',
            name='geojson_url',
        ),
        migrations.AddField(
            model_name='queryobject',
            name='next_query',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='query_api.QueryObject'),
            preserve_default=False,
        ),
    ]
